/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import oru.inf.InfDB;
import javax.swing.JOptionPane;

/**
 *
 * @author juliadyrebrant
 */
public class AvdelningsInformation extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private String avdid;
    private String avdelning;

    /**
     * Creates new form AvdelningsInformation
     */
    public AvdelningsInformation(InfDB idb, String inloggadAnvandare, String avdelning, String avdid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.avdelning = avdelning; 
        this.avdid = avdid;
        
        initComponents();
        fyllAllaFalt();
    }

    public void fyllAllaFalt()
    {
        Avdelning avdelning = new Avdelning(idb);
        String namn = avdelning.getNamn(avdid);
        txtNamn.setText(namn);
        
        String beskrivning = avdelning.getBeskrivning(avdid);
        txtBeskrivning.setText(beskrivning);
        
        String adress = avdelning.getAdress(avdid);
        txtAdress.setText(adress);
        
        String epost = avdelning.getEpost(avdid);
        txtEpost.setText(epost);
        
        String telefon = avdelning.getTelefon(avdid);
        txtTelefon.setText(telefon);
        
        String stad = avdelning.getStad(avdid);
        txtStad.setText(stad);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        txtBeskrivning = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtStad = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        btnTillbakatillmenyn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNamn.setText("Namn");

        lblBeskrivning.setText("Beskrivning");

        lblAdress.setText("Adress");

        lblEpost.setText("Epost");

        lblTelefon.setText("Telefon");

        lblStad.setText("Stad");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbakatillmenyn.setText("Tillbaka till menyn");
        btnTillbakatillmenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakatillmenynActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStad)
                    .addComponent(lblTelefon)
                    .addComponent(lblEpost)
                    .addComponent(lblAdress)
                    .addComponent(lblNamn)
                    .addComponent(lblBeskrivning))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbakatillmenyn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnSpara)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBeskrivning, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamn))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEpost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdress))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefon))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStad)
                    .addComponent(txtStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTillbakatillmenyn))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakatillmenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakatillmenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true); 
    }//GEN-LAST:event_btnTillbakatillmenynActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
                                         
    String namn = txtNamn.getText().trim();
    String beskrivning = txtBeskrivning.getText().trim();
    String adress = txtAdress.getText().trim();
    String epost = txtEpost.getText().trim();
    String telefon = txtTelefon.getText().trim();
    String stad = txtStad.getText().trim();

    if (!namn.matches("^[a-zA-ZåäöÅÄÖ ]+$")) {
        JOptionPane.showMessageDialog(this, "Namn får endast innehålla bokstäver.");
        return;
    }

    if (beskrivning.length() < 5 || beskrivning.length() > 50) {
        JOptionPane.showMessageDialog(this, "Beskrivning måste vara mellan 5 och 50 tecken.");
        return;
    }

    if (!adress.matches(".*[a-zA-ZåäöÅÄÖ].*") || !adress.matches(".*\\d.*")) {
        JOptionPane.showMessageDialog(this, "Adress måste innehålla både bokstäver och siffror.");
        return;
    }

    if (!epost.endsWith("@ngo.org")) {
        JOptionPane.showMessageDialog(this, "E-post måste sluta på @ngo.org.");
        return;
    }

    if (!telefon.matches("^\\+?\\d{1,10}$")) {
        JOptionPane.showMessageDialog(this, "Telefon får innehålla max 10 siffror och valfritt + i början.");
        return;
    }

    if (!stad.matches("^[a-zA-ZåäöÅÄÖ ]+$")) {
        JOptionPane.showMessageDialog(this, "Stad får endast innehålla bokstäver.");
        return;
    }

    // Sparar till databasen
    try {
        String sql = "UPDATE AVDELNING SET NAMN = '" + namn + 
                     "', BESKRIVNING = '" + beskrivning + 
                     "', ADRESS = '" + adress + 
                     "', EPOST = '" + epost + 
                     "', TELEFON = '" + telefon + 
                     "', STAD = '" + stad + 
                     "' WHERE AVD_ID = " + avdid + ";";
        idb.update(sql);
        JOptionPane.showMessageDialog(this, "Uppgifterna har sparats.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvdelningsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvdelningsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvdelningsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvdelningsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new AvdelningsInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbakatillmenyn;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtBeskrivning;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtStad;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
