/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import java.util.ArrayList;
import oru.inf.InfDB;

/**
 *
 * @author karlb
 */
public class LaggTillHandlaggare extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private Avdelning avdelning;
    /**
     * Creates new form LaggTillHandlaggare
     */
    public LaggTillHandlaggare(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.avdelning = new Avdelning(idb);
        fyllAvdelningar();
        fyllAnsvarighetsOmraden();
        
        //När man trycker på knappen "Generera lösenord" körs metoden  btnGenereraLosenordActionPerformed
        btnGenereraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereraLosenordActionPerformed(evt);
            }
        });
    }
    
    public void fyllAvdelningar()
    {
        try{
        cbxAvdelningar.removeAllItems();
        ArrayList<String> avdelningar = avdelning.hamtaAllaNamn();
        for(String namn: avdelningar)
        {
            cbxAvdelningar.addItem(namn);
        }
        }   
        catch(Exception ex){
        System.out.println(ex.getMessage());    
    } 
    }
    
    public void fyllAnsvarighetsOmraden()
    {
        Anstalld anstalld = new Anstalld(idb);
        try{
        cbxAnsvarighetsOmrade.removeAllItems();
        ArrayList<String> omraden = anstalld.hamtaAnsvarighetsomraden();
        for(String namn: omraden)
        {
            cbxAnsvarighetsOmrade.addItem(namn);
        }
        }   
        catch(Exception ex){
        System.out.println(ex.getMessage());    
    } 
    }
    //Metod för att generera ett lösenord till nyanställd
    private String genereraLosenord() {
        String losenordTecken = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                + "abcdefghijklmnopqrstuvwxyz"
                + "0123456789!@#$%";
        String losenord = "";
        int langdLosenord = 10; //Hur långt lösenordet ska vara
        
        for (int i = 0; i < langdLosenord; i++) {
            int index = (int)(Math.random() * losenordTecken.length());
            losenord += losenordTecken.charAt(index);  
        }
        return losenord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLosenord = new javax.swing.JTextField();
        btnTillbakaTillMenyn = new javax.swing.JButton();
        lblEfternamn = new javax.swing.JLabel();
        txtEfternamn = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        txtFornamn = new javax.swing.JTextField();
        lblLosenord = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        btnGenereraLosenord = new javax.swing.JButton();
        lblAdress = new javax.swing.JLabel();
        cbxAvdelningar = new javax.swing.JComboBox<>();
        txtAnstallningsdatum = new javax.swing.JTextField();
        lblAnsvarighetsOmrade = new javax.swing.JLabel();
        lblAnstallningsdatum = new javax.swing.JLabel();
        cbxAnsvarighetsOmrade = new javax.swing.JComboBox<>();
        lblTelefon = new javax.swing.JLabel();
        txtEpost = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        lblEpost = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbakaTillMenyn.setText("Tillbaka Till Menyn");
        btnTillbakaTillMenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenynActionPerformed(evt);
            }
        });

        lblEfternamn.setText("Efternamn");

        txtFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornamnActionPerformed(evt);
            }
        });

        lblLosenord.setText("Lösenord");

        lblFornamn.setText("Förnamn");

        btnGenereraLosenord.setText("Generera lösenord");
        btnGenereraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereraLosenordActionPerformed(evt);
            }
        });

        lblAdress.setText("Adress");

        cbxAvdelningar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAnsvarighetsOmrade.setText("Ansvarighetsområde:");

        lblAnstallningsdatum.setText("Anställningsdatum");

        cbxAnsvarighetsOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));

        lblTelefon.setText("Telefon");

        btnSpara.setText("Spara ändringar");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblEpost.setText("Epost");

        lblAvdelning.setText("Avdelning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbakaTillMenyn)
                        .addGap(18, 18, 18)
                        .addComponent(btnSpara))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnstallningsdatum)
                            .addComponent(lblAnsvarighetsOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtEfternamn, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtAnstallningsdatum, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(cbxAvdelningar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxAnsvarighetsOmrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(btnGenereraLosenord)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenereraLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnstallningsdatum)
                    .addComponent(txtAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(cbxAvdelningar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsvarighetsOmrade)
                    .addComponent(cbxAnsvarighetsOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTillbakaTillMenyn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaTillMenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenynActionPerformed

    private void txtFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornamnActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
    String fornamn = txtFornamn.getText();
    String efternamn = txtEfternamn.getText();
    String epost = txtEpost.getText();
    String losenord = txtLosenord.getText(); // Antas vara genererat via knapp
    String adress = txtAdress.getText();
    String telefon = txtTelefon.getText();
    String anstallningsdatum = txtAnstallningsdatum.getText();

    Validering validering = new Validering(idb);
    Anstalld anstalld = new Anstalld(idb);

    String felmeddelanden = "";

    // Validering
    if (validering.arTextFaltTomt(fornamn) || !anstalld.kontrolleraFornamn(fornamn)) {
        felmeddelanden += "- Fel i förnamn: Minst 3 tecken och max 25.\n";
    }
    if (validering.arTextFaltTomt(efternamn) || !anstalld.kontrolleraEfternamn(efternamn)) {
        felmeddelanden += "- Fel i efternamn: Minst 3 tecken och max 50.\n";
    }
    if (validering.arTextFaltTomt(epost) || !anstalld.kontrolleraEpost(epost)) {
        felmeddelanden += "- Fel i e-post: Måste sluta med @example.com och innehålla endast giltiga tecken.\n";
    }
    if (validering.arTextFaltTomt(adress) || !anstalld.kontrolleraAdress(adress)) {
        felmeddelanden += "- Fel i adress: Mellan 10 och 50 tecken.\n";
    }
    if (validering.arTextFaltTomt(telefon) || !anstalld.kontrolleraTelefon(telefon)) {
        felmeddelanden += "- Fel i telefon: Fältet kan ej vara tomt och måste ha formatet t.ex. 070-123-4567 (med två bindestreck).\n";
    }
    if (validering.arTextFaltTomt(anstallningsdatum) || !validering.kontrolleraDatum(anstallningsdatum)) {
        felmeddelanden += "- Fel i anställningsdatum: Får ej vara tom och måste följa formatet yyyy-mm-dd.\n";
    }

    // Visa valideringsfel om det finns
    if (!felmeddelanden.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Följande fel måste rättas till:\n" + felmeddelanden);
        return; // Avbryt sparandet om fel finns
    }

    try {
        // Hämta vald avdelning
        String valdAvdelning = cbxAvdelningar.getSelectedItem().toString();

        String sqlFraga = "SELECT avdid FROM avdelning WHERE namn = '" + valdAvdelning + "'";
        String hamtatAvdid = idb.fetchSingle(sqlFraga);
        
        // Hämta valt ansvarighetsområde
        String valdAnsvarighetsOmrade = cbxAnsvarighetsOmrade.getSelectedItem().toString();
        

        // Hämta nästa aid
        String maxAidSql = "SELECT MAX(aid) FROM anstalld";
        String maxAidStr = idb.fetchSingle(maxAidSql);
        int nyAid = 1;
        if (maxAidStr != null) {
            nyAid = Integer.parseInt(maxAidStr) + 1;
        }

        // Sätt in i DB
        String insertFraga = "INSERT INTO anstalld (aid, fornamn, efternamn, epost, losenord, "
                + "adress, telefon, anstallningsdatum, avdelning) "
                + "VALUES ('" + nyAid + "', '" + fornamn + "', '" + efternamn + "', '"
                + epost + "', '" + losenord + "', '" + adress + "', '" + telefon + "', '"
                + anstallningsdatum + "', '" + hamtatAvdid + "')";

        idb.insert(insertFraga);
        
        String insertHandlaggare = "INSERT INTO handlaggare (aid, ansvarighetsomrade, mentor) " +
                           "VALUES ('" + nyAid + "', '" + valdAnsvarighetsOmrade + "', NULL)";
        idb.insert(insertHandlaggare);

        javax.swing.JOptionPane.showMessageDialog(null, "Handläggare tillagd.");

        // Rensa fälten
        txtFornamn.setText("");
        txtEfternamn.setText("");
        txtEpost.setText("");
        txtLosenord.setText("");
        txtAdress.setText("");
        txtTelefon.setText("");
        txtAnstallningsdatum.setText("");
        fyllAvdelningar();
	fyllAnsvarighetsOmraden();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Fel vid inmatning av uppgifter: " + e.getMessage());
        
    }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnGenereraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereraLosenordActionPerformed
        String slumpatLosenord = genereraLosenord();
        txtLosenord.setText(slumpatLosenord);
    }//GEN-LAST:event_btnGenereraLosenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenereraLosenord;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbakaTillMenyn;
    private javax.swing.JComboBox<String> cbxAnsvarighetsOmrade;
    private javax.swing.JComboBox<String> cbxAvdelningar;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnstallningsdatum;
    private javax.swing.JLabel lblAnsvarighetsOmrade;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtAnstallningsdatum;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtLosenord;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
