/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author juliadyrebrant
 */
public class LandUppgifter extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private String lid;
    private String land;
  

    /**
     * Creates new form LandUppgifter
     */
    public LandUppgifter(InfDB idb, String inloggadAnvandare, String lid, String land) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.lid = lid;
        this.land = land;
        initComponents();
        fyllAllaFalt();
    }
    
    private void fyllAllaFalt()
    {
        Land land = new Land(idb, lid);
        String namn = land.getNamn(lid);
        txtNamn.setText(namn);
        
        String sprak = land.getSprak(lid);
        txtSprak.setText(sprak);
        
        String valuta = land.getValuta(lid);
        txtValuta.setText(valuta);
        
        String tidzon = land.getTidzon(lid);
        txtTidzon.setText(tidzon);
        
        String politiskStruktur = land.getPolitiskStruktur(lid);
        txtPolitisk_Struktur.setText(politiskStruktur);
        
        String ekonomi = land.getEkonomi(lid);
        txtEkonomi.setText(ekonomi);
        }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamn = new javax.swing.JLabel();
        lblSprak = new javax.swing.JLabel();
        lblValuta = new javax.swing.JLabel();
        lblTidzon = new javax.swing.JLabel();
        lblPolitisk_struktur = new javax.swing.JLabel();
        lblEkonomi = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        txtSprak = new javax.swing.JTextField();
        txtValuta = new javax.swing.JTextField();
        txtTidzon = new javax.swing.JTextField();
        txtPolitisk_Struktur = new javax.swing.JTextField();
        txtEkonomi = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        btnTillbakatillmenyn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNamn.setText("Namn");

        lblSprak.setText("Språk");

        lblValuta.setText("Valuta");

        lblTidzon.setText("Tidzon");

        lblPolitisk_struktur.setText("Politisk_Struktur");

        lblEkonomi.setText("Ekonomi");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbakatillmenyn.setText("Tillbaka till menyn");
        btnTillbakatillmenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakatillmenynActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamn)
                    .addComponent(lblEkonomi)
                    .addComponent(lblPolitisk_struktur)
                    .addComponent(lblTidzon)
                    .addComponent(lblValuta)
                    .addComponent(lblSprak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamn)
                    .addComponent(txtSprak)
                    .addComponent(txtValuta)
                    .addComponent(txtTidzon)
                    .addComponent(txtPolitisk_Struktur)
                    .addComponent(txtEkonomi, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(btnTillbakatillmenyn)
                .addGap(18, 18, 18)
                .addComponent(btnSpara)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSprak)
                    .addComponent(txtSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValuta)
                    .addComponent(txtValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTidzon)
                    .addComponent(txtTidzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPolitisk_struktur)
                    .addComponent(txtPolitisk_Struktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEkonomi)
                    .addComponent(txtEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTillbakatillmenyn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakatillmenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakatillmenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakatillmenynActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
    String namn = txtNamn.getText().trim();
    String sprak = txtSprak.getText().trim();
    String valuta = txtValuta.getText().trim();
    String tidzon = txtTidzon.getText().trim();
    String politiskStruktur = txtPolitisk_Struktur.getText().trim();
    String ekonomi = txtEkonomi.getText().trim();

    String felmeddelanden = "";

    Land land = new Land(idb, lid); 
    Validering validering = new Validering(idb);

    // Hämta aktuella värden från databasen
    String gammaltNamn = land.getNamn(lid);
    String gammaltSprak = land.getSprak(lid);
    String gammalValuta = land.getValuta(lid);
    String gammalTidzon = land.getTidzon(lid);
    String gammalPolitiskStruktur = land.getPolitiskStruktur(lid);
    String gammalEkonomi = land.getEkonomi(lid);

    // Kontrollera bara fält som ändrats
    if (!namn.equals(gammaltNamn)) {
        if (!land.kontrolleraLandNamn(namn)) {
            felmeddelanden += "- Fel i namn: Måste vara unikt, 2–100 tecken och inga ogiltiga tecken.\n";
        }
    }

    if (!sprak.equals(gammaltSprak)) {
        if (!land.kontrolleraSprak(sprak)) {
            felmeddelanden += "- Fel i språk: 2–50 tecken, endast bokstäver, siffror, mellanslag, bindestreck och apostrof.\n";
        }
    }

    if (!valuta.equals(gammalValuta)) {
        if (!land.kontrolleraValuta(valuta)) {
            felmeddelanden += "- Fel i valuta: Måste vara ett positivt tal med exakt 4 decimaler (ex. 12.3456).\n";
        }
    }

    if (!tidzon.equals(gammalTidzon)) {
        if (!land.kontrolleraTidzon(tidzon)) {
            felmeddelanden += "- Fel i tidszon: 2–40 tecken, endast bokstäver, siffror, snedstreck, bindestreck, understreck och plustecken.\n";
        }
    }

    if (!politiskStruktur.equals(gammalPolitiskStruktur)) {
        if (!land.kontrolleraPolitiskStruktur(politiskStruktur)) {
            felmeddelanden += "- Fel i politisk struktur: 3–50 tecken, inga ogiltiga tecken.\n";
        }
    }

    if (!ekonomi.equals(gammalEkonomi)) {
        if (!land.kontrolleraEkonomi(ekonomi)) {
            felmeddelanden += "- Fel i ekonomi: 3–50 tecken, inga ogiltiga tecken.\n";
        }
    }

    // Visa eventuella fel
    if (!felmeddelanden.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Följande fel måste rättas till:\n" + felmeddelanden);
        fyllAllaFalt(); // Återställ gamla värden
        return;
    }

    // Uppdatera endast fält som ändrats
    if (!namn.equals(gammaltNamn)) {
        land.setNamn(namn, lid);
    }
    if (!sprak.equals(gammaltSprak)) {
        land.setSprak(sprak, lid);
    }
    if (!valuta.equals(gammalValuta)) {
        land.setValuta(valuta, lid);
    }
    if (!tidzon.equals(gammalTidzon)) {
        land.setTidzon(tidzon, lid);
    }
    if (!politiskStruktur.equals(gammalPolitiskStruktur)) {
        land.setPolitiskStruktur(politiskStruktur, lid);
    }
    if (!ekonomi.equals(gammalEkonomi)) {
        land.setEkonomi(ekonomi, lid);
    }

    JOptionPane.showMessageDialog(null, "Ändringarna har sparats.");
    fyllAllaFalt(); 
}//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new LandUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbakatillmenyn;
    private javax.swing.JLabel lblEkonomi;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPolitisk_struktur;
    private javax.swing.JLabel lblSprak;
    private javax.swing.JLabel lblTidzon;
    private javax.swing.JLabel lblValuta;
    private javax.swing.JTextField txtEkonomi;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtPolitisk_Struktur;
    private javax.swing.JTextField txtSprak;
    private javax.swing.JTextField txtTidzon;
    private javax.swing.JTextField txtValuta;
    // End of variables declaration//GEN-END:variables
}
