/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author karlb
 */
public class Meny extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String inloggadAnvandareAid;
    private Anstalld anstalld;
    private String behorighet;
    private String pid;
    private String projektnamn;
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String inloggadAnvandare) {
        
        
        this.idb = idb;
        anstalld = new Anstalld(idb);
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        String aid = getInloggadAnvandareAid();
        this.inloggadAnvandareAid = aid;

        
        lblAnvandare.setText("Användare: " + inloggadAnvandare);
        
        Inlogg inloggning = new Inlogg(idb);
        behorighet = inloggning.hamtaBehorighet(inloggadAnvandare);
        
        lblBehorighet.setText("Behörighet: " + behorighet);
        
        if(behorighet.equals("Administratör")){
          btnland.setVisible(true);
          btnMinaUppgifter.setVisible(false);  
          btnHallbarhetsMal.setVisible(false);
          btnPersonalLista.setVisible(false);
          btnPartner.setVisible(true);
          btnAvdelning.setVisible(true);
          btnProjekt.setVisible(true);
          btnLaggTillAnstalld.setVisible(true);
          btnTaBortAnstalld.setVisible(true);
          btnSeProjekt.setVisible(false);
          btnSamarbetandePartners.setVisible(false);
          btnSokEfterHandlaggare.setVisible(false);
          btnSokProjekt.setVisible(false);
          
        }
            if(behorighet.equals("Handläggare")){
            btnland.setVisible(false);
            btnMinaUppgifter.setVisible(true);
            btnHallbarhetsMal.setVisible(true);
            btnPersonalLista.setVisible(true);
            btnAvdelning.setVisible(false);
            btnPartner.setVisible(false);
            btnProjekt.setVisible(false);
            btnLaggTillAnstalld.setVisible(false);
            btnTaBortAnstalld.setVisible(false);
            btnSeProjekt.setVisible(true);
            btnSamarbetandePartners.setVisible(true);
            btnSokEfterHandlaggare.setVisible(true);
            btnSokProjekt.setVisible(true);
            }
                if(behorighet.equals("Projektchef")){
                 btnland.setVisible(false);
                 btnMinaUppgifter.setVisible(true); 
                 btnHallbarhetsMal.setVisible(true);
                 btnPersonalLista.setVisible(true);
                 btnPartner.setVisible(false);
                 btnAvdelning.setVisible(false);
                 btnProjekt.setVisible(false);
                 btnLaggTillAnstalld.setVisible(false);
                 btnTaBortAnstalld.setVisible(false);
                 btnSeProjekt.setVisible(true);
                 btnSamarbetandePartners.setVisible(true);
                btnSokEfterHandlaggare.setVisible(true);
                btnSokProjekt.setVisible(true);
                }
    }
    

    public String getInloggadAnvandare()
    {
        return inloggadAnvandare;
    }
    
    public String getInloggadAnvandareAid()
    {
        try{
        String sqlFraga = "SELECT aid from anstalld WHERE epost = '" + inloggadAnvandare + "'";
        String dbAid = idb.fetchSingle(sqlFraga);
        return dbAid;
        
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());    
        }  
        return null;
        }
    
    
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBehorighet = new javax.swing.JLabel();
        lblAnvandare = new javax.swing.JLabel();
        btnMinaUppgifter = new javax.swing.JButton();
        btnland = new javax.swing.JButton();
        btnHallbarhetsMal = new javax.swing.JButton();
        btnAvdelning = new javax.swing.JButton();
        btnPartner = new javax.swing.JButton();
        btnProjekt = new javax.swing.JButton();
        btnLaggTillAnstalld = new javax.swing.JButton();
        btnTaBortAnstalld = new javax.swing.JButton();
        btnPersonalLista = new javax.swing.JToggleButton();
        btnSeProjekt = new javax.swing.JButton();
        btnSokEfterHandlaggare = new javax.swing.JButton();
        btnSamarbetandePartners = new javax.swing.JButton();
        btnSokProjekt = new javax.swing.JButton();
        BtnLoggaut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMinaUppgifter.setText("Mina uppgifter");
        btnMinaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaUppgifterActionPerformed(evt);
            }
        });

        btnland.setText("Land");
        btnland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlandActionPerformed(evt);
            }
        });

        btnHallbarhetsMal.setText("Hållbarhetsmål");
        btnHallbarhetsMal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallbarhetsMalActionPerformed(evt);
            }
        });

        btnAvdelning.setText("Avdelning");
        btnAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvdelningActionPerformed(evt);
            }
        });

        btnPartner.setText("Partner");
        btnPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnerActionPerformed(evt);
            }
        });

        btnProjekt.setText("Projekt");
        btnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektActionPerformed(evt);
            }
        });

        btnLaggTillAnstalld.setText("Lägg Till Anställd");
        btnLaggTillAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillAnstalldActionPerformed(evt);
            }
        });

        btnTaBortAnstalld.setText("Ta Bort Anställd");
        btnTaBortAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortAnstalldActionPerformed(evt);
            }
        });

        btnPersonalLista.setText("Personal");
        btnPersonalLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalListaActionPerformed(evt);
            }
        });

        btnSeProjekt.setText("Se Projekt");
        btnSeProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeProjektActionPerformed(evt);
            }
        });

        btnSokEfterHandlaggare.setText("Sök efter handläggare");
        btnSokEfterHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokEfterHandlaggareActionPerformed(evt);
            }
        });

        btnSamarbetandePartners.setText("Samarbetande partners");
        btnSamarbetandePartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamarbetandePartnersActionPerformed(evt);
            }
        });

        btnSokProjekt.setText("Sök Projekt");
        btnSokProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokProjektActionPerformed(evt);
            }
        });

        BtnLoggaut.setText("Logga ut");
        BtnLoggaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoggautActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBehorighet, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(BtnLoggaut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMinaUppgifter)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTaBortAnstalld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnland, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLaggTillAnstalld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(btnProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPartner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSeProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSamarbetandePartners, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPersonalLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHallbarhetsMal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSokEfterHandlaggare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSokProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBehorighet, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMinaUppgifter)
                        .addComponent(BtnLoggaut)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProjekt)
                    .addComponent(btnSamarbetandePartners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersonalLista)
                    .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSokEfterHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHallbarhetsMal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnland, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeProjekt)
                    .addComponent(btnLaggTillAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSokProjekt)
                    .addComponent(btnTaBortAnstalld))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
     
    this.dispose();
    new MinaUppgifter(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed

    private void btnlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlandActionPerformed
        this.setVisible(false);
        new LandMeny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnlandActionPerformed

    private void btnHallbarhetsMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallbarhetsMalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Hallbarhetsmal(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnHallbarhetsMalActionPerformed

    private void btnAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdelningActionPerformed
        this.setVisible(false);
        new MenyAvdelning(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnAvdelningActionPerformed

    private void btnPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerActionPerformed
        this.setVisible(false);
        new PartnerMeny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnPartnerActionPerformed

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
        this.setVisible(false);
        new ProjektMeny(idb, inloggadAnvandare, projektnamn, pid, behorighet).setVisible(true);
    }//GEN-LAST:event_btnProjektActionPerformed

    private void btnTaBortAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortAnstalldActionPerformed
        this.setVisible(false);
        new TaBortAnstalld(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTaBortAnstalldActionPerformed

    private void btnLaggTillAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillAnstalldActionPerformed
        this.setVisible(false);
        new LaggTillAnstalld(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnLaggTillAnstalldActionPerformed

    private void btnPersonalListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalListaActionPerformed
        this.setVisible(false);
        new PersonalLista(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnPersonalListaActionPerformed

    private void btnSeProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeProjektActionPerformed
        this.setVisible(false);
        new SeProjekt(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnSeProjektActionPerformed

    private void btnSokEfterHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokEfterHandlaggareActionPerformed
        this.setVisible(false);
        new SokEfterHandlaggare(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnSokEfterHandlaggareActionPerformed

    private void btnSamarbetandePartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamarbetandePartnersActionPerformed
        this.setVisible(false);
        new SamarbetandePartners(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnSamarbetandePartnersActionPerformed

    private void btnSokProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokProjektActionPerformed
        this.setVisible(false);
        new SokProjektEfterDatum(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnSokProjektActionPerformed

    private void BtnLoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoggautActionPerformed
    this.dispose();
new Inlogg(idb).setVisible(true);
    }//GEN-LAST:event_BtnLoggautActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoggaut;
    private javax.swing.JButton btnAvdelning;
    private javax.swing.JButton btnHallbarhetsMal;
    private javax.swing.JButton btnLaggTillAnstalld;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnPartner;
    private javax.swing.JToggleButton btnPersonalLista;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JButton btnSamarbetandePartners;
    private javax.swing.JButton btnSeProjekt;
    private javax.swing.JButton btnSokEfterHandlaggare;
    private javax.swing.JButton btnSokProjekt;
    private javax.swing.JButton btnTaBortAnstalld;
    private javax.swing.JButton btnland;
    private javax.swing.JLabel lblAnvandare;
    private javax.swing.JLabel lblBehorighet;
    // End of variables declaration//GEN-END:variables
}
