/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author karlb
 */
public class ProjektUppgifter extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String pid;
    private String projektnamn;
    private Projekt projekt;
    private Validering validering;
    
    /**
     * Creates new form PartnerUppgifter
     */
    public ProjektUppgifter(InfDB idb, String inloggadAnvandare, String projektnamn, String pid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.projektnamn = projektnamn;
        this.pid = pid;
        this.projekt = new Projekt(idb, pid);
        this.validering = new Validering(idb);
        
        initComponents();
        fyllAllaFalt();
    }

    
    public void fyllAllaFalt()
    {
        Projekt projekt = new Projekt(idb, pid);
        String namn = projekt.getProjektNamn(pid);
        txtProjektnamn.setText(namn);
        
        String beskrivning = projekt.getBeskrivning(pid);
        txtBeskrivning.setText(beskrivning);
        
        String startdatum = projekt.getStartDatum(pid);
        txtStartdatum.setText(startdatum);
        
        String slutdatum = projekt.getSlutDatum(pid);
        txtSlutdatum.setText(slutdatum);
        
        String kostnad = projekt.getKostnad(pid);
        txtKostnad.setText(kostnad);
        
        String status = projekt.getStatus(pid);
        txtStatus.setText(status);
        
        String prioritet = projekt.getPrioritet(pid);
        txtPrioritet.setText(prioritet);
        
        String projektchef = projekt.getProjektchef(pid);
        txtProjektChef.setText(projektchef);
        
        String land = projekt.getLand(pid);
        txtLand.setText(land);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProjektNamn = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        txtBeskrivning = new javax.swing.JTextField();
        txtProjektnamn = new javax.swing.JTextField();
        txtStartdatum = new javax.swing.JTextField();
        txtSlutdatum = new javax.swing.JTextField();
        txtKostnad = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtPrioritet = new javax.swing.JTextField();
        txtProjektChef = new javax.swing.JTextField();
        txtLand = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        btnTillbakaTillMenyn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProjektNamn.setText("Projektnamn");

        lblStartdatum.setText("Startdatum");

        lblBeskrivning.setText("Beskrivning");

        lblSlutdatum.setText("Slutdatum");

        lblKostnad.setText("Kostnad");

        lblPrioritet.setText("Prioritet");

        lblStatus.setText("Status");

        lblLand.setText("Land");

        lblProjektchef.setText("ProjektChef");

        txtBeskrivning.setText("jTextField1");

        txtProjektnamn.setText("jTextField1");

        txtStartdatum.setText("jTextField1");

        txtSlutdatum.setText("jTextField1");

        txtKostnad.setText("jTextField1");

        txtStatus.setText("jTextField1");

        txtPrioritet.setText("jTextField1");

        txtProjektChef.setText("jTextField1");

        txtLand.setText("jTextField1");

        btnSpara.setText("Spara ändringar");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbakaTillMenyn.setText("Tillbaka Till Menyn");
        btnTillbakaTillMenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenynActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLand, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLand, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProjektChef, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbakaTillMenyn)
                .addGap(18, 18, 18)
                .addComponent(btnSpara)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektNamn)
                    .addComponent(txtProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartdatum)
                    .addComponent(txtStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSlutdatum)
                    .addComponent(txtSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnad)
                    .addComponent(txtKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrioritet)
                    .addComponent(txtPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProjektchef)
                    .addComponent(txtProjektChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(txtLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTillbakaTillMenyn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        String projektnamn = txtProjektnamn.getText();
    String beskrivning = txtBeskrivning.getText();
    String startdatum = txtStartdatum.getText();
    String slutdatum = txtSlutdatum.getText();
    String kostnad = txtKostnad.getText();
    String status = txtStatus.getText();
    String prioritet = txtPrioritet.getText();
    String projektchef = txtProjektChef.getText();
    String land = txtLand.getText();

    String felmeddelanden = "";

    if (!(validering.kontrolleraProjektnamn(projektnamn) && !validering.arTextFaltTomt(projektnamn))) {
        felmeddelanden += "- Fel i projektnamn: Kontrollera att det är 3–50 tecken och inga specialtecken.\n";
    }

    if (!validering.kontrolleraProjektnamnUnikt(projektnamn, pid)) {
    felmeddelanden += "- Fel i projektnamn: Namnet finns redan i databasen.\n";
    }
    
    if (!(validering.kontrolleraProjektBeskrivning(beskrivning) && !validering.arTextFaltTomt(beskrivning))) {
        felmeddelanden += "- Fel i beskrivning: Mellan 10 och 500 tecken. Endast bokstäver, siffror, mellanslag, punkt, komma och bindestreck.\n";
    }
    if (!(validering.kontrolleraDatum(startdatum) && !validering.arTextFaltTomt(startdatum))) {
        felmeddelanden += "- Fel i startdatum: Kan ej vara tomt och måste följa format yyyy-MM-dd.\n";
    }
    if (!(validering.kontrolleraSlutDatum(pid, slutdatum) && !validering.arTextFaltTomt(slutdatum))) {
        felmeddelanden += "- Fel i slutdatum: Kan ej vara tomt, måste vara efter startdatum och följa format yyyy-MM-dd.\n";
    }
    if (!(validering.kontrolleraProjektKostnad(kostnad) && !validering.arTextFaltTomt(kostnad))) {
        felmeddelanden += "- Fel i kostnad: Kan ej vara tomt och måste vara ett tal >= 0.\n";
    }
    if (!(validering.kontrolleraProjektStatus(status) && !validering.arTextFaltTomt(status))) {
        felmeddelanden += "- Fel i status: Måste vara Planerat, Pågående eller Avslutat.\n";
    }
    if (!(validering.kontrollleraProjektPrioritet(prioritet) && !validering.arTextFaltTomt(prioritet))) {
        felmeddelanden += "- Fel i prioritet: Måste vara Låg, Medel eller Hög.\n";
    }
    if (!(validering.kontrolleraProjektchef(projektchef) && !validering.arTextFaltTomt(prioritet))) {
        felmeddelanden += "- Fel i projektchef: Angivet namn måste vara en befintlig handläggare. Vänligen se till att både förnamn och efternamn har stor bokstav.\n";
    }
    if (!(validering.kontrolleraLandFinns(land) && !validering.arTextFaltTomt(land))) {
        felmeddelanden += "- Fel i land: Fältet kan ej vara tomt och landet måste finnas i databasen.\n";
    }

    if (!felmeddelanden.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Följande fel måste rättas till:\n" + felmeddelanden);
        fyllAllaFalt();
        return;
    }

    // Om inga fel:
    projekt.setProjektNamn(projektnamn, pid);
    projekt.setBeskrivning(beskrivning, pid);
    projekt.setStartDatum(startdatum, pid);
    projekt.setSlutDatum(slutdatum, pid);
    projekt.setKostnad(kostnad, pid);
    projekt.setStatus(status, pid);
    projekt.setPrioritet(prioritet, pid);
    projekt.setProjektchef(projektchef, pid);
    projekt.setLand(land, pid);

    JOptionPane.showMessageDialog(null, "Ändringarna har sparats.");
	fyllAllaFalt();

        
        
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnTillbakaTillMenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenynActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ProjektUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbakaTillMenyn;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblProjektNamn;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtBeskrivning;
    private javax.swing.JTextField txtKostnad;
    private javax.swing.JTextField txtLand;
    private javax.swing.JTextField txtPrioritet;
    private javax.swing.JTextField txtProjektChef;
    private javax.swing.JTextField txtProjektnamn;
    private javax.swing.JTextField txtSlutdatum;
    private javax.swing.JTextField txtStartdatum;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
