/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import oru.inf.InfDB;

/**
 *
 * @author karlb
 */
public class ProjektProjektchefMeny extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String inloggadAnvandareAid;
    private Projekt projekt;
    private String valtProjekt;
    private String pid;
    /**
     * Creates new form ProjektProjektchefMeny
     */
    public ProjektProjektchefMeny(InfDB idb, String inloggadAnvandare, String inloggadAnvandareAid, String valtProjekt, String pid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.inloggadAnvandareAid = inloggadAnvandareAid;
        this.valtProjekt = valtProjekt;
        this.pid = pid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLaggTillPartnerProjekt = new javax.swing.JButton();
        btnAndraUppgifterProjekt = new javax.swing.JButton();
        btnTillbakaTillMenyn = new javax.swing.JButton();
        btnTabortPartnerProjekt = new javax.swing.JButton();
        btnLaggTillHandlaggareProjekt = new javax.swing.JButton();
        btnTaBortHandlaggareProjekt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLaggTillPartnerProjekt.setText("Lägg till partner");
        btnLaggTillPartnerProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillPartnerProjektActionPerformed(evt);
            }
        });

        btnAndraUppgifterProjekt.setText("Ändra uppgifter");
        btnAndraUppgifterProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraUppgifterProjektActionPerformed(evt);
            }
        });

        btnTillbakaTillMenyn.setText("Tillbaka Till Menyn");
        btnTillbakaTillMenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenynActionPerformed(evt);
            }
        });

        btnTabortPartnerProjekt.setText("Ta bort partner");
        btnTabortPartnerProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabortPartnerProjektActionPerformed(evt);
            }
        });

        btnLaggTillHandlaggareProjekt.setText("Lägg till handläggare");
        btnLaggTillHandlaggareProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillHandlaggareProjektActionPerformed(evt);
            }
        });

        btnTaBortHandlaggareProjekt.setText("Ta bort handläggare");
        btnTaBortHandlaggareProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortHandlaggareProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTaBortHandlaggareProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLaggTillHandlaggareProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTabortPartnerProjekt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLaggTillPartnerProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAndraUppgifterProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTillbakaTillMenyn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAndraUppgifterProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaggTillPartnerProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTabortPartnerProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaggTillHandlaggareProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaBortHandlaggareProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnTillbakaTillMenyn)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillPartnerProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillPartnerProjektActionPerformed
        this.dispose();
        new LaggTillPartnerProjekt(idb, inloggadAnvandare, inloggadAnvandareAid, valtProjekt, pid).setVisible(true);   
        
    }//GEN-LAST:event_btnLaggTillPartnerProjektActionPerformed

    private void btnAndraUppgifterProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraUppgifterProjektActionPerformed
       this.dispose();
        new ProjektUppgifterProjektchef(idb, inloggadAnvandare, inloggadAnvandareAid, valtProjekt, pid).setVisible(true); 
        
    }//GEN-LAST:event_btnAndraUppgifterProjektActionPerformed

    private void btnTillbakaTillMenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenynActionPerformed

    private void btnTabortPartnerProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabortPartnerProjektActionPerformed

    }//GEN-LAST:event_btnTabortPartnerProjektActionPerformed

    private void btnLaggTillHandlaggareProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillHandlaggareProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaggTillHandlaggareProjektActionPerformed

    private void btnTaBortHandlaggareProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortHandlaggareProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaBortHandlaggareProjektActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektProjektchefMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ProjektProjektchefMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifterProjekt;
    private javax.swing.JButton btnLaggTillHandlaggareProjekt;
    private javax.swing.JButton btnLaggTillPartnerProjekt;
    private javax.swing.JButton btnTaBortHandlaggareProjekt;
    private javax.swing.JButton btnTabortPartnerProjekt;
    private javax.swing.JButton btnTillbakaTillMenyn;
    // End of variables declaration//GEN-END:variables
}
