/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author karlb
 */
public class SamarbetandePartners extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String inloggadAnvandareAid;
    
    /**
     * Creates new form SamarbetandePartners
     */
    public SamarbetandePartners(InfDB idb, String inloggadAnvandare, String inloggadAnvandareAid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.inloggadAnvandareAid = inloggadAnvandareAid;
        initComponents();
        fyllUppgifter();
    }

    
    public void fyllUppgifter() {
    try {
        Partner partner = new Partner(idb);
        
        DefaultTableModel model = (DefaultTableModel) tblSamarbetandePartnerUppgifter.getModel();
        model.setRowCount(0);

        // Lista att spara projekt-ID:n där den inloggade är involverad
        ArrayList<String> projektIdn = new ArrayList<>();

        // 1. Hämtar alla pid i ans_proj där aid är den inloggades aid.
        String sqlTilldeladeProjekt = "SELECT pid FROM ans_proj WHERE aid = " + inloggadAnvandareAid;
        ArrayList<String> tilldeladeProjekt = idb.fetchColumn(sqlTilldeladeProjekt);
        if (tilldeladeProjekt != null) {
            for (String pid : tilldeladeProjekt) {
                if (!projektIdn.contains(pid)) {
                    projektIdn.add(pid);
                }
            }
        }

        // 2. Hämtar alla pid där den inloggade är projektchef
        String sqlProjektchefProjekt = "SELECT pid FROM projekt WHERE projektchef = " + inloggadAnvandareAid;
        ArrayList<String> chefProjekt = idb.fetchColumn(sqlProjektchefProjekt);
        if (chefProjekt != null) {
            for (String pid : chefProjekt) {
                if (!projektIdn.contains(pid)) {
                    projektIdn.add(pid);
                }
            }
        }

        // 3. Hämta partneruppgifter för varje projekt
        for (String pid : projektIdn) {
    String sqlPartner = 
    "SELECT partner.namn, partner.kontaktperson, partner.kontaktepost, " +
    "partner.telefon, partner.adress, partner.branch, partner.stad " +
    "FROM partner " +
    "JOIN projekt_partner ON partner.pid = projekt_partner.partner_pid " +
    "WHERE projekt_partner.pid = " + pid;

    ArrayList<HashMap<String, String>> partnerUppgifter = idb.fetchRows(sqlPartner);

    if (partnerUppgifter != null) {
        for (HashMap<String, String> rad : partnerUppgifter) {
        String stadId = rad.get("stad");
        String stadNamn = partner.getStadNamn(stadId);

            if (stadNamn == null) {
                stadNamn = "Okänd stad";
            }    
            
            model.addRow(new Object[]{
            rad.get("namn"),
            rad.get("kontaktperson"),
            rad.get("kontaktepost"),
            rad.get("telefon"),
            rad.get("adress"),
            rad.get("branch"),
            stadNamn
            });
        }
    }
}

    } catch (InfException ex) {
        System.out.println("Fel vid hämtning av partneruppgifter: " + ex.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbaka = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSamarbetandePartnerUppgifter = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbaka.setText("Tillbaka till menyn");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        tblSamarbetandePartnerUppgifter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Namn", "Kontaktperson", "Kontaktepost", "Telefon", "Adress", "Branch", "Stad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSamarbetandePartnerUppgifter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SamarbetandePartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SamarbetandePartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SamarbetandePartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SamarbetandePartners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SamarbetandePartners().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSamarbetandePartnerUppgifter;
    // End of variables declaration//GEN-END:variables
}
