/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import oru.inf.InfDB;

/**
 *
 * @author karlb
 */
public class SeProjekt extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private String inloggadAnvandareAid;
    private String behorighet;
    /**
     * Creates new form SeProjekt
     */
    public SeProjekt(InfDB idb, String inloggadAnvandare, String inloggadAnvandareAid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.inloggadAnvandareAid = inloggadAnvandareAid;
        initComponents();
        Inlogg inloggning = new Inlogg(idb);
        behorighet = inloggning.hamtaBehorighet(inloggadAnvandare);
        
        if(behorighet.equals("Projektchef")){
            btnProjektAnsvarig.setVisible(true);
            btnStatistikKostnad.setVisible(true);
        }
        else{
            btnProjektAnsvarig.setVisible(false);
            btnStatistikKostnad.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProjektTilldelad = new javax.swing.JButton();
        btnProjektAvdelning = new javax.swing.JButton();
        btnTillbakaTillMenyn = new javax.swing.JButton();
        btnProjektAnsvarig = new javax.swing.JButton();
        btnStatistikKostnad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProjektTilldelad.setText("Projekt jag är tilldelad på");
        btnProjektTilldelad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektTilldeladActionPerformed(evt);
            }
        });

        btnProjektAvdelning.setText("Projekt på min avdelning");
        btnProjektAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektAvdelningActionPerformed(evt);
            }
        });

        btnTillbakaTillMenyn.setText("Tillbaka Till Menyn");
        btnTillbakaTillMenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenynActionPerformed(evt);
            }
        });

        btnProjektAnsvarig.setText("Projekt jag är projektansvarig för");
        btnProjektAnsvarig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektAnsvarigActionPerformed(evt);
            }
        });

        btnStatistikKostnad.setText("Statistik över kostnad för projekt");
        btnStatistikKostnad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikKostnadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnTillbakaTillMenyn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProjektAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProjektTilldelad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProjektAnsvarig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStatistikKostnad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnProjektAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProjektTilldelad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProjektAnsvarig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStatistikKostnad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnTillbakaTillMenyn)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaTillMenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenynActionPerformed

    private void btnProjektTilldeladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektTilldeladActionPerformed
        this.dispose();
        new ProjektTilldelad(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnProjektTilldeladActionPerformed

    private void btnProjektAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektAvdelningActionPerformed
        this.dispose();
        new ProjektMinAvdelning(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnProjektAvdelningActionPerformed

    private void btnProjektAnsvarigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektAnsvarigActionPerformed
        this.dispose();
        new ValjProjektProjektchef(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnProjektAnsvarigActionPerformed

    private void btnStatistikKostnadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikKostnadActionPerformed
        this.dispose();
        new StatistikKostnadProjekt(idb, inloggadAnvandare, inloggadAnvandareAid).setVisible(true);
    }//GEN-LAST:event_btnStatistikKostnadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SeProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProjektAnsvarig;
    private javax.swing.JButton btnProjektAvdelning;
    private javax.swing.JButton btnProjektTilldelad;
    private javax.swing.JButton btnStatistikKostnad;
    private javax.swing.JButton btnTillbakaTillMenyn;
    // End of variables declaration//GEN-END:variables
}
