/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author karlb
 */
public class SokEfterHandlaggare extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String inloggadAnvandareAid;
    private Anstalld anstalld;
    private Validering validering;
    /**
     * Creates new form SokEfterHandlaggare
     */
    public SokEfterHandlaggare(InfDB idb, String inloggadAnvandare, String inloggadAnvandareAid) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.inloggadAnvandareAid = inloggadAnvandareAid;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSokEpost = new javax.swing.JLabel();
        txtSokningEpost = new javax.swing.JTextField();
        btnSokNamn = new javax.swing.JButton();
        btnTillbakaTillMenyn = new javax.swing.JButton();
        txtSokningEfternamn = new javax.swing.JTextField();
        txtSokningFornamn = new javax.swing.JTextField();
        lblFornamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblSokEpost1 = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        btnSokEpost1 = new javax.swing.JButton();
        BtnTillbakaTillForegaende = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSokEpost.setText("Sök efter en handläggare via epost:");

        btnSokNamn.setText("Sök");
        btnSokNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokNamnActionPerformed(evt);
            }
        });

        btnTillbakaTillMenyn.setText("Tillbaka till Menyn");
        btnTillbakaTillMenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenynActionPerformed(evt);
            }
        });

        lblFornamn.setText("Förnamn:");

        lblEpost.setText("Epost:");

        lblSokEpost1.setText("Sök efter en handläggare via för- och efternamn:");

        lblEfternamn.setText("Efternamn:");

        btnSokEpost1.setText("Sök");
        btnSokEpost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokEpost1ActionPerformed(evt);
            }
        });

        BtnTillbakaTillForegaende.setText("Tillbaka till föregående sida");
        BtnTillbakaTillForegaende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaTillForegaendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BtnTillbakaTillForegaende)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbakaTillMenyn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSokningEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSokningFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(txtSokningEfternamn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSokNamn)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSokEpost1)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSokEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblSokEpost1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSokEpost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSokningEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEpost)
                    .addComponent(btnSokEpost1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblSokEpost1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSokningFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFornamn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSokningEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEfternamn))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSokNamn)
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaTillMenyn)
                    .addComponent(BtnTillbakaTillForegaende))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokNamnActionPerformed
        validering = new Validering(idb);
        anstalld = new Anstalld(idb);

        String fornamn = txtSokningFornamn.getText();
        String efternamn = txtSokningEfternamn.getText();

    if (validering.arTextFaltTomt(fornamn) || validering.arTextFaltTomt(efternamn)) {
        JOptionPane.showMessageDialog(null, "En av rutorna saknar text, vänligen försök igen.");
        return;
    }
    

    try {
        String avdelning = anstalld.getAvdelning(inloggadAnvandareAid);

        String sqlFraga = "SELECT anstalld.aid " +
                     "FROM anstalld " +
                     "JOIN handlaggare ON anstalld.aid = handlaggare.aid " +
                     "WHERE anstalld.avdelning = '" + avdelning + "' " +
                     "AND (anstalld.fornamn = '" + fornamn + "') " +
                     "AND anstalld.efternamn = '" + efternamn + "'";

        String aid = idb.fetchSingle(sqlFraga);

        if (aid == null || aid.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingen handläggare hittades. Vänligen försök igen.");
        } else {
            
            
            Handlaggare handlaggare = new Handlaggare(idb, inloggadAnvandare, aid);
            handlaggare.setVisible(true);
            this.dispose();
        }

    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Fel vid sökning: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSokNamnActionPerformed

    private void btnTillbakaTillMenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenynActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenynActionPerformed

    private void btnSokEpost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokEpost1ActionPerformed
        validering = new Validering(idb);
        anstalld = new Anstalld(idb);

        
        String sokning = txtSokningEpost.getText();

    if (validering.arTextFaltTomt(sokning)) {
        JOptionPane.showMessageDialog(null, "Rutan får inte vara tom, vänligen försök igen.");
        return;
    }

    try {
        String avdelning = anstalld.getAvdelning(inloggadAnvandareAid);

        String sqlFraga = "SELECT anstalld.aid " +
                     "FROM anstalld " +
                     "JOIN handlaggare ON anstalld.aid = handlaggare.aid " +
                     "WHERE anstalld.avdelning = '" + avdelning + "' " +
                     "AND anstalld.epost = '" + sokning + "'";

        String aid = idb.fetchSingle(sqlFraga);

        if (aid == null || aid.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingen handläggare hittades. Vänligen försök igen.");
        } else {
            
            
            Handlaggare handlaggare = new Handlaggare(idb, inloggadAnvandare, aid);
            handlaggare.setVisible(true);
            this.dispose();
        }
        }

        catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Fel vid sökning: " + e.getMessage());
    }

   
    
    }//GEN-LAST:event_btnSokEpost1ActionPerformed

    private void BtnTillbakaTillForegaendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaTillForegaendeActionPerformed
this.dispose();
new Meny(idb, inloggadAnvandare).setVisible(true);                                                        
    }//GEN-LAST:event_BtnTillbakaTillForegaendeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SokEfterHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SokEfterHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SokEfterHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SokEfterHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SokEfterHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTillbakaTillForegaende;
    private javax.swing.JButton btnSokEpost1;
    private javax.swing.JButton btnSokNamn;
    private javax.swing.JButton btnTillbakaTillMenyn;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblSokEpost;
    private javax.swing.JLabel lblSokEpost1;
    private javax.swing.JTextField txtSokningEfternamn;
    private javax.swing.JTextField txtSokningEpost;
    private javax.swing.JTextField txtSokningFornamn;
    // End of variables declaration//GEN-END:variables
}
