/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author karlb
 */
public class TaBortPartner extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String inloggadAnvandareAid;
    private Partner partner;
    private String valdPartner;
    private String pid;
    /**
     * Creates new form TaBortPartner
     */
    public TaBortPartner(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        
        partner = new Partner(idb);  // skapa objektet som används i fyllCombobox()
        fyllCombobox(); 
    }
    
    public void fyllCombobox()
    {
        try{
        cbxPartner.removeAllItems();
        ArrayList<String> allaProjekt = partner.hamtaAllaNamn();
        for(String namn: allaProjekt)
        {
            cbxPartner.addItem(namn);
        }
        }   
        catch(Exception ex){
        System.out.println(ex.getMessage());    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartner = new javax.swing.JLabel();
        cbxPartner = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        btnTillbakaTillMeny = new javax.swing.JButton();
        BtnTillbakaTillForegaende = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPartner.setText("Partner:");

        cbxPartner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnTillbakaTillMeny.setText("Tillbaka till menyn");
        btnTillbakaTillMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenyActionPerformed(evt);
            }
        });

        BtnTillbakaTillForegaende.setText("Tillbaka till föregående sida");
        BtnTillbakaTillForegaende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaTillForegaendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTillbakaTillForegaende)
                        .addGap(26, 26, 26)
                        .addComponent(btnTillbakaTillMeny))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnTaBort))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPartner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaBort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaTillMeny)
                    .addComponent(BtnTillbakaTillForegaende))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
         try {
        String valdStrang = cbxPartner.getSelectedItem().toString();
        this.valdPartner = valdStrang;

        // Hämta pid för vald partner
        String sqlFraga = "SELECT pid FROM partner WHERE namn = '" + valdStrang + "'";
        String hamtatPid = idb.fetchSingle(sqlFraga);

        if (hamtatPid != null) {
            int svar = JOptionPane.showConfirmDialog(null,
                    "Är du säker på att du vill ta bort \"" + valdStrang + "\"?",
                    "Bekräfta borttagning",
                    JOptionPane.YES_NO_OPTION);

            if (svar == JOptionPane.YES_OPTION) {
                
                // Ta bort partner från projekt_partner
                String kontrollPartnerFraga = "SELECT * FROM projekt_partner WHERE partner_pid = " + hamtatPid;
                HashMap<String, String> partnerCheck = idb.fetchRow(kontrollPartnerFraga);
                if (partnerCheck != null) {
                    String deletePartnerFraga = "DELETE FROM projekt_partner WHERE partner_pid = " + hamtatPid;
                    idb.delete(deletePartnerFraga);
                }
                
                // Ta bort partnern från partner-tabellen
                String deleteProjektFraga = "DELETE FROM partner WHERE pid = " + hamtatPid;
                idb.delete(deleteProjektFraga);

                JOptionPane.showMessageDialog(null, valdStrang + " har tagits bort.");
                fyllCombobox(); // uppdatera listan med projekt
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kunde inte hitta partnens PID.");
        }

    } catch (InfException ex) {
        System.out.println("Fel vid borttagning: " + ex.getMessage());
        JOptionPane.showMessageDialog(null, "Något gick fel vid borttagningen.");
    }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenyActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenyActionPerformed

    private void BtnTillbakaTillForegaendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaTillForegaendeActionPerformed
        this.dispose();
        new PartnerMeny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_BtnTillbakaTillForegaendeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TaBortPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTillbakaTillForegaende;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbakaTillMeny;
    private javax.swing.JComboBox<String> cbxPartner;
    private javax.swing.JLabel lblPartner;
    // End of variables declaration//GEN-END:variables
}
