/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applikation;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author filippacolbin
 */
public class TaBortAvdelning extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form TaBortAvdelning
     */
    public TaBortAvdelning(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        fyllAvdelning();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAvdelning = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        btnTillbakaTillMeny = new javax.swing.JButton();
        BtnTillbakaTillForegaende = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnTillbakaTillMeny.setText("Tillbaka till menyn");
        btnTillbakaTillMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillMenyActionPerformed(evt);
            }
        });

        BtnTillbakaTillForegaende.setText("Tillbaka till föregående sida");
        BtnTillbakaTillForegaende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaTillForegaendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTaBort))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BtnTillbakaTillForegaende)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbakaTillMeny)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaBort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaTillMeny)
                    .addComponent(BtnTillbakaTillForegaende))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fyllAvdelning() {
        try {
            ArrayList<String> avdelningar = idb.fetchColumn("SELECT namn FROM avdelning");
            cbAvdelning.removeAllItems();
            for (String namn : avdelningar) {
                cbAvdelning.addItem(namn);   
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av avdelning: " + e.getMessage());
        }
    }

    
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
       try {
            String valdAvdelning = (String) cbAvdelning.getSelectedItem();
            
            if (valdAvdelning != null) {
                int svar = JOptionPane.showConfirmDialog(this, "Vill du verkligen ta bort avdelning '"
                + valdAvdelning + "'?", "Bekräfta", JOptionPane.YES_NO_OPTION);
                
                if (svar == JOptionPane.YES_OPTION) {
                    idb.delete("DELETE FROM avdelning WHERE namn = '" + valdAvdelning + "'");
                    cbAvdelning.removeItem(valdAvdelning);
                    JOptionPane.showMessageDialog(this, "Avdelning togs bort.");
                }
            }     
        } catch (InfException e ) {
            JOptionPane.showMessageDialog(this, "Fel vid borttagning:" + e.getMessage());
        }                     
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillMenyActionPerformed
        this.dispose();
        new Meny(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillMenyActionPerformed

    private void BtnTillbakaTillForegaendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaTillForegaendeActionPerformed
        this.dispose();
        new MenyHanteraAvdelning(idb, inloggadAnvandare).setVisible(true);
    }//GEN-LAST:event_BtnTillbakaTillForegaendeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
               }
            }
           //Fångar eventuella fel
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TaBortAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        // Skapar koppling till databasen
        InfDB idb = null;
        try {
            idb = new InfDB("SDGSweden");
        } catch (Exception e) {
            e.printStackTrace();
        }

        String inloggadAnvandare = "root";

        final InfDB finalIdb = idb;
        final String finalInloggadAnvandare = inloggadAnvandare;
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortAvdelning(finalIdb, finalInloggadAnvandare).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTillbakaTillForegaende;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbakaTillMeny;
    private javax.swing.JComboBox<String> cbAvdelning;
    // End of variables declaration//GEN-END:variables
}
